version: '3'
services:
  db:
    image: postgres:10.5
    environment:
      - PGUSER=postgres
      - PGPASSWORD=root

  mail:
    image: sj26/mailcatcher
    ports:
      - 3080:1080

  web:
    build: .
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pb-platform
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mail
