development:
  adapter: redis
  url: redis://app.scoutlook.ca:6379
  channel_prefix: scout_development

staging:
  adapter: redis
  url: redis://app.scoutlook.ca:6379
  channel_prefix: scout_staging

test:
  adapter: async

production:
  adapter: redis
  url: redis://app.scoutlook.ca:6379
  channel_prefix: scout_production
