development:
  adapter: redis
  url: redis://3.98.62.116:6379
  channel_prefix: scout_development

staging:
  adapter: redis
  url: redis://scoutlook-production-ro.zh4knt.ng.0001.cac1.cache.amazonaws.com:6379
  channel_prefix: scout_staging

test:
  adapter: async

production:
  adapter: redis
  url: redis://app.scoutlook.ca:6379
  channel_prefix: scout_production
