development: scoutlook-production-ro.zh4knt.ng.0001.cac1.cache.amazonaws.com:6379
test: localhost:6379
staging: scoutlook-production-ro.zh4knt.ng.0001.cac1.cache.amazonaws.com:6379
fi: localhost:6379
production: scoutlook-production-ro.zh4knt.ng.0001.cac1.cache.amazonaws.com:6379
